name: screenshot_modes
description: easy automatics way for take screenshot for your app , screenshot mode  work as plugin for device_preview package
version: 1.0.1
repository: https://github.com/Ali1Ammar/screenshot_modes
homepage: https://github.com/Ali1Ammar/screenshot_modes

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0

  provider: ^6.1.2
  platform: ^3.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
