name: screenshot_modes
description: easy automatics way for take screenshot for your app , screenshot mode  work as plugin for device_preview package
version: 1.0.0
repository: https://github.com/Ali1Ammar/screenshot_modes
homepage: https://github.com/Ali1Ammar/screenshot_modes

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.1.0

  provider: ^6.0.3
  platform: ^3.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
